FROM ghcr.io/ksev/ostree-images/base:latest

# Copy the compiled akmods from these ublue images so i dont have to build against newest kernel release
COPY --from=ghcr.io/ublue-os/akmods-nvidia:main-41 /rpms /tmp/rpms

RUN find /tmp/rpms && \
    rpm-ostree install /tmp/rpms/ublue-os/ublue-os-nvidia*.rpm && \
    rpm-ostree install /tmp/rpms/kmods/kmod-nvidia*.rpm && \
    ostree container commit

LABEL NAME base-nv
LABEL VERSION latest
