ARG RPMFUSION_FREE="https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-38.noarch.rpm"
ARG RPMFUSION_NON_FREE="https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-38.noarch.rpm"

FROM ghcr.io/ksev/ostree-images/base:latest

# Copy the compiled akmods from these ublue images so i dont have to build against newest kernel release
COPY --from=ghcr.io/ublue-os/akmods-nvidia:main-38-535 /rpms /tmp/akmods-rpms

RUN rpm-ostree install /tmp/akmods-rpms/ublue-os/ublue-os-nvidia-addons-*.rpm && \
    source /tmp/akmods-rpms/kmods/nvidia-vars.535 && \
    rpm-ostree install \
        xorg-x11-drv-${NVIDIA_PACKAGE_NAME}-{,cuda-,devel-,kmodsrc-,power-}${NVIDIA_FULL_VERSION} \
        xorg-x11-drv-${NVIDIA_PACKAGE_NAME}-libs.i686 \
        nvidia-container-toolkit nvidia-vaapi-driver supergfxctl ${VARIANT_PKGS} \
        /tmp/akmods-rpms/kmods/kmod-${NVIDIA_PACKAGE_NAME}-${KERNEL_VERSION}-${NVIDIA_AKMOD_VERSION}.fc${RELEASE}.rpm && \ 
    ostree container commit

LABEL NAME base-nv
LABEL VERSION latest
