---
- name: Base image Playbook
  hosts: localhost
  tasks:
  - name: configure rpm-ostree auto updates
    copy:
      src: rpm-ostreed.conf
      dest: /etc/rpm-ostreed.conf
      mode: '0644'

  - name: configure flatpak auto updates
    copy:
      src: flatpak-automatic/
      dest: /etc/systemd/system/
      mode: '0644'

  - name: Enable Auto update ostree
    systemd: 
      name: rpm-ostreed-automatic.timer
      enabled: true

  - name: Enable Auto update flatpak
    systemd: 
      name: flatpak-automatic.timer
      enabled: true

  - name: Remove Firefox
    community.general.rpm_ostree_pkg:
      name:
      - firefox
      - firefox-langpacks
      state: absent

  - name: Add base packages
    community.general.rpm_ostree_pkg:
      name: 
      - distrobox
      - gnome-tweaks
      - steam-devices
      state: present

#  - name: Download VRR Copr
#    shell: wget https://copr.fedorainfracloud.org/coprs/kylegospo/gnome-vrr/repo/fedora-$(rpm -E %fedora)/kylegospo-gnome-vrr-fedora-$(rpm -E %fedora).repo -O /etc/yum.repos.d/_copr_kylegospo-gnome-vrr.repo

#  - name: Build VRR Copr
#    shell: rpm-ostree override replace --experimental --from repo=copr:copr.fedorainfracloud.org:kylegospo:gnome-vrr mutter gnome-control-center gnome-control-center-filesystem
